import { ServiceItem } from "@/app/types/service";

export const SERVICES: ServiceItem[] = [
  {
    icon: "/ibu-mengandung.svg",
    title: "Rawatan Ibu Mengandung",
    category: "family",
    desc: "Kami menyediakan perkhidmatan seperti <i>ultrasound scan baby</i>, buka buku pink, ujian kehamilan, minum air gula dan lain-lain",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/rawatan-pesakit-luar.png",
    title: "Rawatan Pesakit Luar",
    category: "family",
    desc: "Kami menyediakan rawatan kesihatan yang biasa dilakukan di klinik kami, contohnya seperti rawatan demam, batuk, selsema, gastrik atau GERD, migrain dan lain-lain",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/pemeriksaan-kesihatan.png",
    title: "Pemeriksaan Kesihatan",
    category: "family",
    desc: "Kami menyediakan perkhidmatan untuk pelbagai jenis pemeriksaan kesihatan seperti pelajar, pekerja asing, GDL dan e-hailing.",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/ultrasound-scan.png",
    title: "Ultrasound Scan",
    category: "family",
    desc: "Kami menggunakan mesin Ultrasound yang terkini yang boleh mengimbas secara 2d, 3d, 4d & 5d.",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/pemeriksaan-kuning-bayi.png",
    title: "Pemeriksaan Kuning Bayi",
    category: "family",
    desc: "Inovaso perubatan terkini yang dikembangkan secara eksklusif untuk menghilangkan kesulitan dan kesakitan bayi",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/ujian-darah.png",
    title: "Ujian Darah",
    category: "family",
    desc: "Kami menyediakan perkhidmatan ujian saringan kesihatan melalui pengambilan darah",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/cucian-luka.png",
    title: "Cucian Luka",
    category: "family",
    desc: "Kami menyediakan perkhidmatan cucian luka seperti luka kencing manis, luka selepas operasi, luka kemalangan dan lain-lain",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/rawatan-asma.png",
    title: "Rawatan Asma & Sedut Kahak",
    category: "family",
    desc: "Kami menyediakan rawatan nebulizer untuk pesakit asma. Kami juga melakukan sedutan kahak bagi melegakan pesakit yang batuk terbahak",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/vaksinasi-imunisasi.png",
    title: "Vaksinasi & Imunisasi",
    category: "family",
    desc: "Dapatkan vaksin untuk pengendali makanan iaitu vaksin typhoid, vaksin influenza dan Umrah & Hajj",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/housecall-doctor.png",
    title: "Housecall Doctor",
    category: "family",
    desc: "Kami menyediakan perkhidmatan rawatan doktor ke rumah anda",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/covid-rtk-pcr.png",
    title: "Covid RTK & PCR",
    category: "family",
    desc: "Kami menyediakan perkhidmatan ujian covid RTK dan PCR secara temu janji",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/perancangan-keluarga.png",
    title: "Perancangan Keluarga",
    category: "family",
    desc: "Kami menyediakan perkhidmatan suntikan IM Depo bagi mencegah kehamilan.",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/kesihatan-wanita.png",
    title: "Kesihatan Wanita",
    category: "family",
    desc: "Kami menyediakan perkhidmatan ujian untuk mengetahui tahap kesuburan anda dan ujian Pap Smear untuk saringan kanser pangkal rahim.",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/perkhidmatan-kaunseling.png",
    title: "Perkhidmatan Kaunseling",
    category: "family",
    desc: "Kami juga menyediakan perkhidmatan kaunseling",
    button: "Ketahui lebih lanjut",
  },
];

export const SERVICES_MINI: ServiceItem[] = [
  {
    icon: "/services/rawatan-pesakit-luar.png",
    category: "family",
    title: "Rawatan Pesakit Luar",
    desc: "Kami menyediakan rawatan kesihatan yang biasa dilakukan di klinik kami, contohnya seperti rawatan demam, batuk, selsema, gastrik atau GERD, migrain dan lain-lain",
  },
  {
    icon: "/services/pemeriksaan-kesihatan.png",
    category: "family",
    title: "Pemeriksaan Kesihatan",
    desc: "Kami menyediakan perkhidmatan untuk pelbagai jenis pemeriksaan kesihatan seperti pelajar, pekerja asing, GDL dan e-hailing.",
  },
  {
    icon: "/services/ultrasound-scan.png",
    category: "family",
    title: "Ultrasound Scan",
    desc: "Kami menggunakan mesin Ultrasound yang terkini yang boleh mengimbas secara 2d, 3d, 4d & 5d.",
  },
  {
    icon: "/services/pemeriksaan-kuning-bayi.png",
    category: "family",
    title: "Pemeriksaan Kuning Bayi",
    desc: "Inovaso perubatan terkini yang dikembangkan secara eksklusif untuk menghilangkan kesulitan dan kesakitan bayi",
  },
  {
    icon: "/services/ujian-darah.png",
    category: "family",
    title: "Ujian Darah",
    desc: "Kami menyediakan perkhidmatan ujian saringan kesihatan melalui pengambilan darah",
  },
  {
    icon: "/services/cucian-luka.png",
    category: "family",
    title: "Cucian Luka",
    desc: "Kami menyediakan perkhidmatan cucian luka seperti luka kencing manis, luka selepas operasi, luka kemalangan dan lain-lain",
  },
];
