import { ServiceItem } from "@/app/types/service";

export const SERVICES: ServiceItem[] = [
  {
    icon: "/ibu-mengandung.svg",
    title: "General Health Consultation",
    category: "general",
    desc: "Discuss health concerns, receive personlaized advice, and develop a plan for maintaining or imporving overall well-being",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/rawatan-pesakit-luar.png",
    title: "Skin Analysis",
    category: "general",
    desc: "Provides an in-depth assessment of your skin's health using expert visual inspection to identify issues like pigmentation, wrinkles, texture, and hidration",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/pemeriksaan-kesihatan.png",
    title: "Women's Health Consultation",
    category: "general",
    desc: "Provides an in-depth assessment about menstrual health, hormonal balance, fertility planning and reproductive health.",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/ultrasound-scan.png",
    title: "Lactation Consultation",
    category: "general",
    desc: "Provides support and guidance on breastfeeding practises from a certified professional to help mothers with issues like latching, milk supply, and comfort during feedings",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/pemeriksaan-kuning-bayi.png",
    title: "Posture Analysis",
    category: "general",
    desc: "Provides a physical assessment to evaluate the alignment and balance of the body's segments to identify imbalances and correct posture",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/ujian-darah.png",
    title: "Mental Health Assessment",
    category: "general",
    desc: "Provides a structured evaluation to understand a person’s emotional, psychological, and social well-being. It helps identify early signs of stress, anxiety, depression, or other concerns, and provides guidance for maintaining a healthy mind.",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/cucian-luka.png",
    title: "Diet Assessment",
    category: "general",
    desc: "a simple evaluation of a person’s eating habits and nutrition to understand whether their diet supports their health goals and overall well-being.",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/rawatan-asma.png",
    title: "Body Composition Analysis",
    category: "general",
    desc: "Provides a comprehensive breakdown of your body's components beyond simple weight, detailing percentages of fat, muscle, bone, and water. ",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/vaksinasi-imunisasi.png",
    title: "Signature Facial",
    category: "face",
    desc: "The Signature facial is a simple yet effective way to care for your skin. It focuses on the essentials — cleansing, gentle exfoliation extractions, and hydration — to leave your skin feeling refreshed and healthy. Perfect for routine maintenance",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/housecall-doctor.png",
    title: "Deep Cleansing Facial",
    category: "face",
    desc: "A deep cleansing facial that targets excess oil, impurities, and dead skin cells to unclog pores and improve skin texture.",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/covid-rtk-pcr.png",
    title: "Hydrafacial",
    category: "face",
    desc: "The HydraFacial is an advanced treatment designed to restore hydration and vitality to the skin. Using advanced technology, it combines deep cleansing, gentle exfoliation, extractions, and intense hydration in one session.",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/perancangan-keluarga.png",
    title: "Acne Clear Facial",
    category: "face",
    desc: "Acne is a complex dermatological condition that often requires medical expertise to address underlying factors, not just surface symptoms.",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/kesihatan-wanita.png",
    title: "Skin Tightening Facial",
    category: "face",
    desc: "The skin tightening facial is designed to firm and lift the skin, restoring a more youthful appearance. Using advanced technology, this treatment stimulates collagen production, improves elasticity, and smooths fine lines",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/perkhidmatan-kaunseling.png",
    title: "Glow Boost Facial",
    category: "face",
    desc: "The Glow Boost Facial is all about restoring radiance and vitality to your skin. This treatment combines deep cleansing, gentle exfoliation, and an infusion of Vitamin C serums to brighten, even out skin tone, and protect against environmental stressors.",
    button: "Ketahui lebih lanjut",
  },
  {
    icon: "/services/perkhidmatan-kaunseling.png",
    title: "Glow Boost Facial",
    category: "face",
    desc: "The Glow Boost Facial is all about restoring radiance and vitality to your skin. This treatment combines deep cleansing, gentle exfoliation, and an infusion of Vitamin C serums to brighten, even out skin tone, and protect against environmental stressors.",
    button: "Ketahui lebih lanjut",
  },
];

export const SERVICES_MINI: ServiceItem[] = [
  {
    icon: "/services/rawatan-pesakit-luar.png",
    category: "family",
    title: "Rawatan Pesakit Luar",
    desc: "Kami menyediakan rawatan kesihatan yang biasa dilakukan di klinik kami, contohnya seperti rawatan demam, batuk, selsema, gastrik atau GERD, migrain dan lain-lain",
  },
  {
    icon: "/services/pemeriksaan-kesihatan.png",
    category: "family",
    title: "Pemeriksaan Kesihatan",
    desc: "Kami menyediakan perkhidmatan untuk pelbagai jenis pemeriksaan kesihatan seperti pelajar, pekerja asing, GDL dan e-hailing.",
  },
  {
    icon: "/services/ultrasound-scan.png",
    category: "family",
    title: "Ultrasound Scan",
    desc: "Kami menggunakan mesin Ultrasound yang terkini yang boleh mengimbas secara 2d, 3d, 4d & 5d.",
  },
  {
    icon: "/services/pemeriksaan-kuning-bayi.png",
    category: "family",
    title: "Pemeriksaan Kuning Bayi",
    desc: "Inovaso perubatan terkini yang dikembangkan secara eksklusif untuk menghilangkan kesulitan dan kesakitan bayi",
  },
  {
    icon: "/services/ujian-darah.png",
    category: "family",
    title: "Ujian Darah",
    desc: "Kami menyediakan perkhidmatan ujian saringan kesihatan melalui pengambilan darah",
  },
  {
    icon: "/services/cucian-luka.png",
    category: "family",
    title: "Cucian Luka",
    desc: "Kami menyediakan perkhidmatan cucian luka seperti luka kencing manis, luka selepas operasi, luka kemalangan dan lain-lain",
  },
];
